//! Dynamic Hugging Face model catalog.
//!
//! sherpa-onnx can only run models exported by its own scripts, so the catalog
//! is limited to the maintainer's account (`csukuangfj`) and to the families
//! `transcribe.rs` can execute: offline NeMo CTC / NeMo transducer exports
//! plus the streaming ones (NeMo/Nemotron transducer, T-one CTC).
//!
//! Flow: a build-time snapshot (`resources/hf-catalog.json`, generated by the
//! `hf_snapshot` bin) seeds a cache file in the app data dir; when the model
//! list is requested and the cache is older than 24 h it is refreshed from the
//! HF API in the background (the UI is notified via `hf-catalog-updated`).
//! A descriptor is stored next to downloaded files so a downloaded model keeps
//! working even if its catalog entry disappears.

use crate::models::{self, Engine, ModelDef, ModelFile};
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{OnceLock, RwLock};
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use tauri::path::BaseDirectory;
use tauri::{AppHandle, Emitter, Manager};

const HF_AUTHOR: &str = "csukuangfj";
const CACHE_FILE: &str = "hf-catalog.json";
const RESOURCE_FILE: &str = "resources/hf-catalog.json";
const UPDATED_EVENT: &str = "hf-catalog-updated";
const DESCRIPTOR_FILE: &str = "dictosaurus-model.json";
const REFRESH_INTERVAL: Duration = Duration::from_secs(24 * 60 * 60);

static CACHE_PATH: OnceLock<PathBuf> = OnceLock::new();
static CATALOG: RwLock<Option<HfCatalog>> = RwLock::new(None);
static REFRESHING: AtomicBool = AtomicBool::new(false);

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HfFile {
    /// Path inside the HF repo.
    pub path: String,
    pub size: u64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HfModel {
    /// Full repo id, e.g. `csukuangfj/sherpa-onnx-nemo-ctc-en-conformer-large`.
    pub repo_id: String,
    pub label: String,
    pub engine: Engine,
    /// "multilingual" or comma-separated language codes.
    pub languages: String,
    pub total_bytes: u64,
    /// Canonical order: CTC = [model, tokens]; transducer = [encoder, decoder, joiner, tokens].
    pub files: Vec<HfFile>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HfCatalog {
    /// Unix seconds of the snapshot / last refresh.
    pub generated_at: u64,
    pub models: Vec<HfModel>,
}

// --- Runtime cache ---

pub fn init(app: &AppHandle) {
    let Ok(data_dir) = app.path().app_data_dir() else {
        log::warn!("[hf-catalog] app_data_dir unavailable");
        return;
    };
    let cache = data_dir.join(CACHE_FILE);

    if !cache.is_file() {
        match app.path().resolve(RESOURCE_FILE, BaseDirectory::Resource) {
            Ok(resource) => {
                if let Err(e) = std::fs::copy(&resource, &cache) {
                    log::warn!("[hf-catalog] seed cache from bundled snapshot: {e}");
                }
            }
            Err(e) => log::warn!("[hf-catalog] bundled snapshot not found: {e}"),
        }
    }

    match read_catalog(&cache) {
        Ok(catalog) => *CATALOG.write().unwrap() = Some(catalog),
        Err(e) => log::warn!("[hf-catalog] load cache: {e}"),
    }
    let _ = CACHE_PATH.set(cache);
}

fn read_catalog(path: &std::path::Path) -> Result<HfCatalog, String> {
    let raw = std::fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    serde_json::from_str(&raw).map_err(|e| format!("parse {}: {e}", path.display()))
}

pub fn current() -> Option<HfCatalog> {
    CATALOG.read().unwrap().clone()
}

/// Refreshes the catalog from the HF API in the background if the cache is
/// older than 24 h. Never blocks; on failure the old cache is kept.
pub fn maybe_refresh(app: &AppHandle) {
    let Some(cache) = CACHE_PATH.get() else {
        return;
    };

    let fresh = std::fs::metadata(cache)
        .and_then(|m| m.modified())
        .ok()
        .and_then(|mtime| mtime.elapsed().ok())
        .is_some_and(|age| age < REFRESH_INTERVAL);
    if fresh || REFRESHING.swap(true, Ordering::SeqCst) {
        return;
    }

    let app = app.clone();
    let cache = cache.clone();
    tauri::async_runtime::spawn(async move {
        match fetch_from_hf().await {
            Ok(catalog) => {
                if let Err(e) = write_catalog_atomically(&cache, &catalog) {
                    log::warn!("[hf-catalog] write cache: {e}");
                } else {
                    log::info!("[hf-catalog] refreshed: {} models", catalog.models.len());
                    *CATALOG.write().unwrap() = Some(catalog);
                    let _ = app.emit(UPDATED_EVENT, ());
                }
            }
            Err(e) => log::warn!("[hf-catalog] refresh failed, keeping old cache: {e}"),
        }
        REFRESHING.store(false, Ordering::SeqCst);
    });
}

fn write_catalog_atomically(path: &std::path::Path, catalog: &HfCatalog) -> Result<(), String> {
    let raw = serde_json::to_string_pretty(catalog).map_err(|e| e.to_string())?;
    let tmp = path.with_extension("json.tmp");
    std::fs::write(&tmp, raw).map_err(|e| format!("write {}: {e}", tmp.display()))?;
    std::fs::rename(&tmp, path).map_err(|e| format!("rename: {e}"))
}

// --- Model identity ---

fn repo_name(repo_id: &str) -> &str {
    repo_id.rsplit('/').next().unwrap_or(repo_id)
}

fn repo_id_from_model_id(model_id: &str) -> Option<&str> {
    model_id.strip_prefix(models::HF_ID_PREFIX)
}

pub fn model_id(repo_id: &str) -> String {
    format!("{}{repo_id}", models::HF_ID_PREFIX)
}

/// Per-model download directory: `<models>/hf/<repo name>`.
pub fn download_dir(model_id: &str) -> Option<PathBuf> {
    let repo_id = repo_id_from_model_id(model_id)?;
    Some(models::models_dir()?.join("hf").join(repo_name(repo_id)))
}

fn to_def(model: &HfModel) -> ModelDef {
    let dir = repo_name(&model.repo_id);
    ModelDef {
        id: model_id(&model.repo_id),
        label: model.label.clone(),
        size_label: human_size(model.total_bytes),
        description: model.repo_id.clone(),
        engine: model.engine,
        languages: model.languages.clone(),
        feature_dim: None,
        files: model
            .files
            .iter()
            .map(|f| ModelFile {
                rel_path: format!("hf/{dir}/{}", f.path),
                url: format!(
                    "https://huggingface.co/{}/resolve/main/{}",
                    model.repo_id, f.path
                ),
                bytes_hint: f.size,
            })
            .collect(),
    }
}

pub fn def_by_id(model_id: &str) -> Option<ModelDef> {
    let repo_id = repo_id_from_model_id(model_id)?;

    if let Some(catalog) = CATALOG.read().unwrap().as_ref() {
        if let Some(model) = catalog.models.iter().find(|m| m.repo_id == repo_id) {
            return Some(to_def(model));
        }
    }

    // Fall back to the descriptor stored next to downloaded files.
    let descriptor = download_dir(model_id)?.join(DESCRIPTOR_FILE);
    let raw = std::fs::read_to_string(descriptor).ok()?;
    let model: HfModel = serde_json::from_str(&raw).ok()?;
    Some(to_def(&model))
}

pub fn persist_descriptor(model_id: &str) -> Result<(), String> {
    let repo_id = repo_id_from_model_id(model_id).ok_or_else(|| "not an HF model".to_string())?;
    let catalog = CATALOG.read().unwrap();
    let model = catalog
        .as_ref()
        .and_then(|c| c.models.iter().find(|m| m.repo_id == repo_id))
        .ok_or_else(|| "model not in catalog".to_string())?;

    let dir = download_dir(model_id).ok_or_else(|| "models directory not initialized".to_string())?;
    std::fs::create_dir_all(&dir).map_err(|e| format!("create dir: {e}"))?;
    let raw = serde_json::to_string_pretty(model).map_err(|e| e.to_string())?;
    std::fs::write(dir.join(DESCRIPTOR_FILE), raw).map_err(|e| format!("write descriptor: {e}"))
}

// --- Listing for the UI ---

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct HfCatalogInfo {
    pub generated_at: u64,
    pub models: Vec<models::ModelInfo>,
}

pub fn catalog_status() -> Option<HfCatalogInfo> {
    let catalog = current()?;
    let models = catalog
        .models
        .iter()
        .map(|m| {
            let def = to_def(m);
            models::ModelInfo {
                downloaded: models::resolve_paths(&def).is_some(),
                streaming: def.engine.is_streaming(),
                id: def.id,
                label: def.label,
                size_label: def.size_label,
                description: def.description,
                engine: def.engine,
                languages: def.languages,
            }
        })
        .collect();
    Some(HfCatalogInfo {
        generated_at: catalog.generated_at,
        models,
    })
}

fn human_size(bytes: u64) -> String {
    let mb = bytes as f64 / 1_000_000.0;
    if mb >= 1000.0 {
        format!("~{:.1} GB", mb / 1000.0)
    } else {
        format!("~{:.0} MB", mb)
    }
}

// --- Fetching and filtering (shared by the runtime refresh and `hf_snapshot`) ---

#[derive(Deserialize)]
struct RepoListEntry {
    id: String,
}

#[derive(Deserialize)]
struct TreeEntry {
    #[serde(rename = "type")]
    kind: String,
    path: String,
    #[serde(default)]
    size: u64,
}

/// Queries the HF API and builds the filtered catalog of offline NeMo models.
pub async fn fetch_from_hf() -> Result<HfCatalog, String> {
    let client = reqwest::Client::builder()
        .user_agent("Dictosaurus/0.1")
        .build()
        .map_err(|e| e.to_string())?;

    let list_url = format!(
        "https://huggingface.co/api/models?author={HF_AUTHOR}&search=sherpa-onnx&limit=500"
    );
    let repos: Vec<RepoListEntry> = get_json(&client, &list_url).await?;
    if repos.len() >= 500 {
        log::warn!("[hf-catalog] repo list may be truncated at 500 entries");
    }

    let mut models = Vec::new();
    for repo in &repos {
        let name = repo_name(&repo.id);
        if !is_candidate(name) {
            continue;
        }
        let tree_url = format!("https://huggingface.co/api/models/{}/tree/main", repo.id);
        let entries: Vec<TreeEntry> = match get_json(&client, &tree_url).await {
            Ok(entries) => entries,
            Err(e) => {
                log::warn!("[hf-catalog] tree {}: {e}", repo.id);
                continue;
            }
        };
        let files: Vec<HfFile> = entries
            .into_iter()
            .filter(|e| e.kind == "file")
            .map(|e| HfFile {
                path: e.path,
                size: e.size,
            })
            .collect();

        let Some((engine, selected)) = classify(name, &files) else {
            continue;
        };
        models.push(HfModel {
            repo_id: repo.id.clone(),
            label: name.strip_prefix("sherpa-onnx-").unwrap_or(name).to_string(),
            engine,
            languages: detect_languages(name),
            total_bytes: selected.iter().map(|f| f.size).sum(),
            files: selected,
        });
    }

    models.sort_by(|a, b| a.repo_id.cmp(&b.repo_id));
    Ok(HfCatalog {
        generated_at: SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0),
        models,
    })
}

async fn get_json<T: serde::de::DeserializeOwned>(
    client: &reqwest::Client,
    url: &str,
) -> Result<T, String> {
    let response = client
        .get(url)
        .send()
        .await
        .map_err(|e| format!("request: {e}"))?;
    if !response.status().is_success() {
        return Err(format!("HTTP {}", response.status()));
    }
    let body = response.bytes().await.map_err(|e| format!("body: {e}"))?;
    serde_json::from_slice(&body).map_err(|e| format!("parse: {e}"))
}

/// Repo-name prefilter: NeMo exports (offline and streaming), Nemotron and
/// T-one streaming models — the families `transcribe.rs` can execute. Canary
/// (unsupported family) and fp16 exports (slow on CPU) are excluded.
fn is_candidate(name: &str) -> bool {
    let family = name.starts_with("sherpa-onnx-nemo-")
        || name.starts_with("sherpa-onnx-nemotron-")
        || name.starts_with("sherpa-onnx-streaming-t-one-");
    family && !name.contains("canary") && !name.contains("fp16")
}

/// Whether a repo name denotes a streaming (online) model.
fn is_streaming(name: &str) -> bool {
    name.contains("streaming") && !name.contains("non-streaming")
}

/// Picks runnable files from a repo tree, or `None` if the repo does not
/// contain a complete model of a supported family.
fn classify(name: &str, files: &[HfFile]) -> Option<(Engine, Vec<HfFile>)> {
    // ONNX external-data exports (e.g. fp32 Parakeet with `encoder.weights`)
    // would need extra files next to the model; skip them.
    if files
        .iter()
        .any(|f| f.path.ends_with(".weights") || f.path.ends_with(".onnx.data"))
    {
        return None;
    }
    let tokens = files.iter().find(|f| f.path == "tokens.txt")?;
    let pick = |role: &str| {
        files
            .iter()
            .find(|f| f.path == format!("{role}.int8.onnx"))
            .or_else(|| files.iter().find(|f| f.path == format!("{role}.onnx")))
    };

    let streaming = is_streaming(name);
    if let (Some(encoder), Some(decoder), Some(joiner)) =
        (pick("encoder"), pick("decoder"), pick("joiner"))
    {
        let engine = if streaming {
            Engine::OnlineTransducer
        } else {
            Engine::NemoTransducer
        };
        return Some((
            engine,
            vec![encoder.clone(), decoder.clone(), joiner.clone(), tokens.clone()],
        ));
    }
    if let Some(model) = pick("model") {
        if streaming {
            // Single-file streaming models: only T-one CTC is supported
            // (streaming NeMo CTC would need another engine kind).
            return name
                .contains("t-one")
                .then(|| (Engine::ToneCtc, vec![model.clone(), tokens.clone()]));
        }
        return Some((Engine::NemoCtc, vec![model.clone(), tokens.clone()]));
    }
    None
}

/// Derives languages from repo-name tokens like `-ru-`, `-russian-`, `stt_de_…`.
fn detect_languages(name: &str) -> String {
    // Names that carry no language tokens.
    if name.contains("parakeet-tdt-0.6b-v3") {
        return "multilingual".into();
    }
    if name.contains("parakeet-tdt-0.6b-v2") || name.contains("parakeet_tdt") {
        return "en".into();
    }

    let mut langs: BTreeSet<&str> = BTreeSet::new();
    for token in name.split(['-', '_', '.']) {
        let code = match token {
            "en" | "ru" | "uk" | "be" | "de" | "fr" | "es" | "it" | "pt" | "pl" | "hr" | "zh"
            | "ja" | "ko" | "vi" | "ar" | "th" | "tr" => token,
            "english" => "en",
            "russian" => "ru",
            "german" => "de",
            "french" => "fr",
            "spanish" => "es",
            "italian" => "it",
            "portuguese" => "pt",
            "chinese" => "zh",
            "japanese" => "ja",
            "korean" => "ko",
            _ => continue,
        };
        langs.insert(code);
    }

    if langs.is_empty() {
        "multilingual".into()
    } else {
        langs.into_iter().collect::<Vec<_>>().join(",")
    }
}
